version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
 build:
  commands:
   - sam build
   - export BUCKET=m6-deploy-bucket
   - sam package --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
 type: zip
 files:
  - samTemplate.yml
  - outputtemplate.yml