AWSTemplateFormatVersion: "2010-09-09"
Description: "template cloudFormation de l'ingestion de RTL radio"

Parameters:

  StateMachineBucket:
    Type: String
    Default: 'm6-deploy-bucket'

  LambdaHelloWorldKey:
    Type: String
    Default: 'hello-world.zip'


Resources:

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"


  HelloWorldLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref StateMachineBucket
        S3Key: !Ref LambdaGetInfoObjectKey
      FunctionName: HelloWorld_test_cicd_axio
      Handler: hello_world.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.8
